"""Creative Pool — hypothesis lifecycle management.

Stores hypotheses generated by the GenerativeReplayEngine. Manages their
lifecycle: pending → confirmed/rejected → promoted (to semantic memory).

Also handles context-matching push to working memory warmup zone.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import numpy as np

from cell_mem.models import MemoryObject, MemoryType

logger = logging.getLogger(__name__)

# Thresholds
PUSH_SIMILARITY_THRESHOLD = 0.6
PROMOTE_CONFIDENCE_THRESHOLD = 0.6
CONFIRM_BOOST = 0.3
REJECT_SUPPRESS_COUNT = 3


class CreativePool:
    """Manages the lifecycle of generative replay hypotheses.

    Constructor-injected dependencies:
    - sqlite_store: SqliteStore
    - embed_model: EmbeddingModel
    - working: WorkingMemory (for push_to_working)
    - semantic: SemanticMemory (for promote_to_semantic)
    """

    _table = "creative_pool"

    def __init__(
        self,
        sqlite_store: "SqliteStore",  # noqa: F821
        embed_model: "EmbeddingModel",  # noqa: F821
        working: Optional["WorkingMemory"] = None,  # noqa: F821
        semantic: Optional["SemanticMemory"] = None,  # noqa: F821
        max_size: int = 1000,
    ):
        from cell_mem.embedding.local import EmbeddingModel
        from cell_mem.memory.semantic import SemanticMemory
        from cell_mem.memory.working import WorkingMemory
        from cell_mem.storage.sqlite_store import SqliteStore

        self._store: SqliteStore = sqlite_store
        self._embed: EmbeddingModel = embed_model
        self._working: Optional[WorkingMemory] = working
        self._semantic: Optional[SemanticMemory] = semantic
        self.max_size = max_size
        logger.info("CreativePool ready (max_size=%d)", max_size)

    # ------------------------------------------------------------------
    # CRUD
    # ------------------------------------------------------------------

    def add(
        self,
        hypothesis_text: str,
        source_seed_ids: List[str] | None = None,
        source_node_ids: List[str] | None = None,
        confidence: float = 0.2,
        seed_content: str = "",
        concept_pair: dict | None = None,
        topic_tags: List[str] | None = None,
        metadata: dict | None = None,
    ) -> MemoryObject:
        """Add a hypothesis to the creative pool."""
        import uuid

        now = datetime.now(timezone.utc).isoformat()
        hid = uuid.uuid4().hex[:16]

        seeds_json = json.dumps(source_seed_ids or [], ensure_ascii=False)
        nodes_json = json.dumps(source_node_ids or [], ensure_ascii=False)
        pair_json = json.dumps(concept_pair or {}, ensure_ascii=False)
        tags_json = json.dumps(topic_tags or [], ensure_ascii=False)
        meta_json = json.dumps(metadata or {}, ensure_ascii=False)

        self._store.execute(
            f"""INSERT INTO {self._table} (
                id, hypothesis_text, source_seed_ids, source_node_ids,
                confidence, status, push_count, ignore_count,
                topic_tags, last_pushed_at, created_at,
                seed_content, concept_pair, stability_count, metadata_json
            ) VALUES (?, ?, ?, ?, ?, 'pending', 0, 0, ?, NULL, ?, ?, ?, 0, ?)""",
            (
                hid, hypothesis_text, seeds_json, nodes_json,
                max(0.1, min(0.3, confidence)),
                tags_json, now, seed_content, pair_json, meta_json,
            ),
        )
        self._store.commit()

        obj = MemoryObject(
            id=hid, content=hypothesis_text,
            memory_type=MemoryType.SEMANTIC,
            confidence=confidence, created_at=now,
            metadata=metadata or {},
        )
        logger.debug("Creative pool added: %s (conf=%.2f)", hid[:8], confidence)
        return obj

    def get(self, hypothesis_id: str) -> Optional[dict]:
        """Retrieve a hypothesis by ID."""
        row = self._store.fetchone(
            f"SELECT * FROM {self._table} WHERE id = ?", (hypothesis_id,)
        )
        return dict(row) if row else None

    def delete(self, hypothesis_id: str) -> bool:
        self._store.execute(
            f"DELETE FROM {self._table} WHERE id = ?", (hypothesis_id,)
        )
        self._store.commit()
        return True

    # ------------------------------------------------------------------
    # Push to Working Memory
    # ------------------------------------------------------------------

    def push_to_working(
        self, context_embedding: np.ndarray, limit: int = 5
    ) -> list:
        """Push matching pending hypotheses to working memory warmup zone.

        Embeds each pending hypothesis, computes cosine similarity with
        context_embedding, and pushes matches > PUSH_SIMILARITY_THRESHOLD.
        """
        if self._working is None:
            return []

        pending = self.get_pending(limit=50)
        if not pending:
            return []

        context_vec = np.asarray(context_embedding, dtype=np.float32)
        ctx_norm = np.linalg.norm(context_vec)
        if ctx_norm == 0:
            return []

        pushed = []
        now = datetime.now(timezone.utc).isoformat()

        for entry in pending[:limit]:
            try:
                hyp_emb = self._embed.embed(entry["hypothesis_text"])
                hyp_norm = np.linalg.norm(hyp_emb)
                if hyp_norm == 0:
                    continue
                sim = float(np.dot(context_vec, hyp_emb) / (ctx_norm * hyp_norm))

                if sim > PUSH_SIMILARITY_THRESHOLD:
                    self._working.add(
                        content=f"[Hypothesis] {entry['hypothesis_text'][:300]}",
                        session_id="creative_pool",
                        base_priority=0.3,
                        metadata={
                            "source": "creative_pool",
                            "hypothesis_id": entry["id"],
                            "similarity": round(sim, 4),
                        },
                    )
                    # Increment push_count
                    self._store.execute(
                        f"UPDATE {self._table} SET push_count = push_count + 1, "
                        f"last_pushed_at = ? WHERE id = ?",
                        (now, entry["id"]),
                    )
                    self._store.commit()
                    pushed.append({"id": entry["id"], "similarity": round(sim, 4)})
            except Exception as exc:
                logger.debug("Push failed for %s: %s", entry["id"][:8], exc)
                continue

        if pushed:
            logger.info("Pushed %d hypotheses to working memory", len(pushed))
        return pushed

    # ------------------------------------------------------------------
    # Feedback Lifecycle
    # ------------------------------------------------------------------

    def record_feedback(self, hypothesis_id: str, confirmed: bool) -> dict:
        """Record user feedback on a hypothesis.

        confirmed=True: confidence += 0.3. If >= 0.6, auto-promote.
        confirmed=False: ignore_count += 1. If >= 3, mark rejected.

        Uses optimistic locking: UPDATE ... WHERE confidence = old_confidence
        prevents lost updates from concurrent feedback calls.
        """
        import json

        entry = self.get(hypothesis_id)
        if entry is None:
            return {"status": "error", "error": f"Hypothesis '{hypothesis_id}' not found"}

        if confirmed:
            old_conf = entry["confidence"]
            new_conf = min(1.0, old_conf + CONFIRM_BOOST)
            new_status = "confirmed"
            should_promote = new_conf >= PROMOTE_CONFIDENCE_THRESHOLD
            if should_promote:
                new_status = "promoted"

            # Optimistic lock: only update if confidence hasn't changed
            self._store.execute(
                f"UPDATE {self._table} SET confidence = ?, status = ? "
                f"WHERE id = ? AND confidence = ?",
                (new_conf, new_status, hypothesis_id, old_conf),
            )
            self._store.commit()

            # Only promote AFTER successful pool update (prevents inconsistent state)
            if should_promote:
                self._promote_to_semantic(entry, new_conf)

            return {"status": "ok", "data": {
                "action": "promoted" if should_promote else "confirmed",
                "hypothesis_id": hypothesis_id,
                "new_confidence": new_conf,
            }}
        else:
            old_ignore = entry["ignore_count"]
            new_ignore = old_ignore + 1
            new_status = "rejected" if new_ignore >= REJECT_SUPPRESS_COUNT else entry["status"]

            # Optimistic lock: only update if ignore_count hasn't changed
            self._store.execute(
                f"UPDATE {self._table} SET ignore_count = ?, status = ? "
                f"WHERE id = ? AND ignore_count = ?",
                (new_ignore, new_status, hypothesis_id, old_ignore),
            )
            self._store.commit()

            return {"status": "ok", "data": {
                "action": "rejected" if new_status == "rejected" else "ignored",
                "hypothesis_id": hypothesis_id,
                "ignore_count": new_ignore,
            }}

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_pending(self, limit: int = 50) -> List[dict]:
        rows = self._store.fetchall(
            f"SELECT * FROM {self._table} WHERE status = 'pending' "
            f"ORDER BY confidence DESC LIMIT ?", (limit,)
        )
        return [dict(r) for r in rows]

    def get_by_status(self, status: str, limit: int = 50) -> List[dict]:
        rows = self._store.fetchall(
            f"SELECT * FROM {self._table} WHERE status = ? "
            f"ORDER BY created_at DESC LIMIT ?", (status, limit)
        )
        return [dict(r) for r in rows]

    def get_rejected_topics(self) -> List[str]:
        """Return topic tags from rejected entries (for bias adjustment in sampling)."""
        rows = self._store.fetchall(
            f"SELECT topic_tags FROM {self._table} WHERE status = 'rejected'"
        )
        topics = set()
        for r in rows:
            try:
                tags = json.loads(r["topic_tags"])
                topics.update(tags)
            except (json.JSONDecodeError, TypeError):
                pass
        return list(topics)

    def count(self) -> int:
        row = self._store.fetchone(f"SELECT COUNT(*) as cnt FROM {self._table}")
        return row["cnt"] if row else 0

    def count_by_status(self) -> Dict[str, int]:
        rows = self._store.fetchall(
            f"SELECT status, COUNT(*) as cnt FROM {self._table} GROUP BY status"
        )
        return {r["status"]: r["cnt"] for r in rows}

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _promote_to_semantic(self, entry: dict, new_confidence: float) -> None:
        """Promote a hypothesis to semantic memory."""
        if self._semantic is None:
            return
        try:
            source_refs = json.loads(entry.get("source_seed_ids", "[]"))
            self._semantic.add(
                content=f"[Insight] {entry['hypothesis_text'][:500]}",
                confidence=new_confidence,
                source_references=source_refs,
                metadata={
                    "source": "generative_replay",
                    "hypothesis_id": entry["id"],
                    "original_confidence": entry["confidence"],
                },
            )
            logger.info("Promoted hypothesis %s → semantic", entry["id"][:8])
        except Exception as exc:
            logger.warning("Failed to promote hypothesis %s: %s", entry["id"][:8], exc)
